# Generated by Django 5.2.9 on 2025-12-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="hardware_id",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="license",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("deactive", "Deactive")], max_length=50
            ),
        ),
    ]
