# Generated by Django 5.2.9 on 2025-12-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0002_license_hardware_id_alter_license_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="hardware_id",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
