# Generated by Django 5.2.9 on 2025-12-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0003_alter_license_hardware_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
