# Generated by Django 5.2.9 on 2025-12-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0004_alter_license_expiration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="expiration_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
